require: rubocop-rspec

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

Layout/LineLength:
  Exclude:
    - "db/seeds.rb"

Style/CaseLikeIf:
  Enabled: false

Metrics/ClassLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 14
